---
- name: Configure Fedora desktop
  hosts: local
  # facts required: roles use ansible_facts['user_dir']
  roles:
    - git
    - zsh
    - opentofu
    - uv
    - fnm
    - gimp
    - qbittorrent
    - bleachbit
    - vlc
    - keepassxc
    - sqlitebrowser
    - fastfetch
    - godot
    - vscode
    - brave
    - flatpak
    - kooha
    - obsidian
    - blender
    - telegram
    - mullvad
    - opensnitch
    - docker
    - solaar
    - golang
    - rust
