---
- name: Install Flatpak
  become: true
  ansible.builtin.dnf5:
    name: flatpak
    state: present

- name: Add Flathub remote
  become: true
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
