---
- name: Install git
  become: true
  ansible.builtin.dnf5:
    name: git
    state: present

- name: Deploy .gitconfig
  ansible.builtin.copy:
    src: gitconfig
    dest: "{{ ansible_user_dir }}/.gitconfig"
    mode: "0644"
